### ISSUE TITLE
Unreliable documentation

### ISSUE THREAD

**Issue by rliscano** [universAAL/platform#6]
I have been trying for several days to install UniversAAL without any success and multiple inconsistency errors. Nearly all tutorials fail at some point in their process. The RDHelloWorld example fails in the run configuration section with felix link errors https://github.com/universAAL/platform/wiki/RD-Hello-World
The Karaf tutorialhttps://github.com/universAAL/platform/wiki/Karaf-runner#How_to_develop_with_Karaf refers to the Hello World example which cannot be executed as well as the creation of a Maven project that is not related to the Eclipse Maven wizard. The Maven tutorial https://github.com/universAAL/applications/wiki/After-development#Testing_your_service_in_universAAL_Karafbased_distribution%7C also fails to since it cannot resolve the  org.universAAL.samples:karaf.feature-archetype:2.0.0 URL that is listed in the tutorial. It is a very frustrating and complicated challenge to get anything developed using universAAL for someone without extensive experience in OSGI containers. I hope that someone can come up with a set of simple and working instructions.

P.S. I was trying to use this for a course of mine and no one in the course could get to work.

**Comment by Alfiva** [comment]
Sorry to hear that. We are aware of some of these problems and are currently working on refactoring the documentation to solve these issues.
In the meantime, I can only suggest to take a look, if you haven't already, at https://github.com/universAAL/platform/wiki/DG-Quick-setup-and-start-guide . For running the hello world and lighting examples you just need to use the command "feature:install uAAL-Ont.Lightning" and drop the compiled jars into the deploy folder.

**Comment by cstockloew** [comment]
Regarding the applications repos: this repo hasn't been updated for a long time. Sorry, but at the moment we cannot provide support. I added a warning comment to the repo and it's wiki that the applications are currently not supported (thanks for the hint).

Regarding the RDHelloWorld example: what felix link error did you get? What version of eclipse do you use? Do you have the latest version of the tools?

**Comment by rliscano** [comment]
Carsten,


Thank you for your reply. I tried several approaches as per the several examples I found on line. The first example I worked on was the Hello World in Eclipse (https://github.com/universAAL/platform/wiki/RD-Hello-World) In this tutorial the recommend the Eclipse Indigo platform listed in the tutorial (https://github.com/universAAL/platform/wiki/RD-Development-Environment).<https://github.com/universAAL/platform/wiki/RD-Development-Environment> The tutorial's text appears to have been modified for the latest version of UAAL v 3.4.0 but examples (screen dumps) show older versions. I was targeting UAAL 3.2.0 but it was not possible to specify in the UAAL tools in Eclipse a project with a higher version than 3.0 even though I updated the Eclipse UAAL tools several times using the Eclipse update and install software options.


When one chooses in the run configuration script UAAL versions higher than 3.0 this leads to incompatibility errors. The only guidance for OSGI versions to use are listed as UAAL compatibility 3.4.0 and Felix 2.0.1. This eventually leads to link errors such as

[link:classpath:runner-links/org.apache.felix.shell-1.4.1.link] is not a valid bundle


I then moved to using Karaf as it seems that this is latest and most reliable OSGI platform. The lighting examples executed well as per https://github.com/universAAL/platform/wiki/Karaf-runner#How_to_develop_with_Karaf The challenge arose from using Karaf to develop an universal application. At this point one has to move to Eclipse again but the instructions of how to develop a Maven project in Eclipse are missing. The Maven wizard requires significant background knowledge to be properly set up that is missing in the tutorial.


At this point I am not certain what documents I could use to get to the point where I can develop a universAAL application.


Ramiro





________________________________

**Comment by rliscano** [comment]
Alvaro,


I believe that I already have managed to get to step 4 after doing other tutorials. When I tried to build the Maven project there are many parameters that have to be set up that I don't understand and appear to be only described in https://github.com/universAAL/applications/wiki/After-development#Testing_your_service_in_universAAL_Karafbased_distribution%7C

but this led to errors in that the artifact could not be found.



Ramiro


________________________________

**Comment by Alfiva** [comment]
Can you describe what you see (or attach a screenshot) when you try to build with Maven? Usually, once you have imported successfully a Maven project in Eclipse, you just need to right click > Run as > Maven install, and you don't need to pass any parameter, it just builds. A different issue would be that you found errors during building and then it fails. That could indicate that something has not been properly set up in a previous step, and we could help with that.

**Comment by jonimoreira** [comment]
Hi,

I'm also having issues to run the Hello World example following the step-by-step. It seems that it is this same issue here, a problem in the "run configuration" part.
I already tried to follow it several times in different environments (e.g. Windows, Ubuntu, Ubuntu within VM) and the error is the same. When creating the uAAL "Run Config", at first, nothing happens: the Run Configurations form of Eclipse should appear, but it doesn't. 
If I "microsoft it" (restart Eclipse) and go to Run Configurations, then the configuration appears there, but when I click it I get null pointer exception. If I check the log, I see an error in the conformanceTools plugin: "Unresolved requirement: Import-Package: org.apache.maven.execution" (I have the screenshot if you want). 
I suggest that someone from UniversAAL team to follow (strictly) the step-by-step from the environment configuration to the hello world execution, i.e. create a clean VM and follow the steps to configure Java, Eclipse, uAAL hello world. For example, you will notice that you recommend Java 8, but the figure shows JDK 1.6, and that in one part it says to use JDK 1.5 for the server side but in other part to use JDK 1.6. 
 I suggest to make either a VM available with everything configured or a kind of script to configure the env (e.g. a Docker file). 
 
I'd like to use UnuiversAAL in my project/framework, which is leveraged by the use of an IoT platform to develop early warning systems (for monitor/detect risks of emergencies). I was considering UniversAAL because the architecture is interesting for me, my research is on semantic interoperability, but now I'm quite worried because it seems this issue has more than 1 year without being treated. 
I think that this is not good for UniversAAL because it causes a big impact for new entrants, especially the type of users I plan to have for my framework (beginner programmers). 

If I can't get this to run in the following days I'll have to change my plans and use another IoT platform. I had seamless installation/configuration of dev env with MS Azure IoT, AWS IoT and even FIWARE. 

Thanks in advance for the support.
Best,
Joao

**Comment by amedranogil** [comment]
Dear Joao,
  I am terribly sorry for your experience, if it is of any consolation, your problem is the typical problem newcommers have when trying out universAAL. This means we need to do a better job in transmmiting the proper procedures.
  First I must ask you to please provide the URL of the documentation you are using, and steps you followed to get there, in other to fix the problem.
  On the mean time, allow me to introduce you to our [Karaf distro](https://github.com/universAAL/distro.karaf/wiki/Karaf-runner), this is the method we recommend, since it is production ready, there is plenty of documentation (although our documentation might be a bit outdated, and it works like a VM or docker (in fact I will shortly add a dockerization of this method).
Executive summary:

1. download, or clone, https://github.com/universAAL/distro.karaf
2. maven install it
3. get either the zip in target or directly work on the assembly. Run bin/karaf(.bat|.sh)
4. this will start universAAL middleware by default. To add specific components use the command `feature:install <name_of_component>`, you may find the full list of components by running the command `feature:list | grep universAAL`
5. you may add your modules (aka bundles) to the deploy folder, this will automatically launch them. As an alternative you can create your own [karaf features](https://karaf.apache.org/manual/latest/provisioning).
6. ???
7. profit :wink: 

Hope this helps you kickstart your project soon.

**Comment by jonimoreira** [comment]
Hi Alejandro,

Thanks for the response. It took me some time to make the things work. 

Regarding the documentation, I used the one that seems the default:
1> https://github.com/universAAL/platform
2> "Be sure to read the wiki page for more information." (link)
3> Just go through all links from the "Introduction" section, e.g.:
Development environment setup - Quick / Details
Creating a "Hello World!" example
Running with Apache Karaf - Quick / Details
Running with Eclipse and Pax Runner - Quick / Details
Running the Lighting Sample

4>Execute the step-by-step in a clean VM and you'll see all issues, small things that make life difficult. 

I could run the lighting example (https://github.com/universAAL/distro.karaf/wiki/Lightning-example) in one Karaf instance. It took me some time to discover that "features:" is "feature:", "addurl" is "repo-add", "bundle:list" to see the ids, among other things. I suggest to also update the doc about these commands. 
In two Karaf instances I could run but not to set one as peer, even with the configuration (org.universAAL.middleware.peer.is_coordinator=false). I'm setting it in the target/assembly/etc/system.properties of the client folder. 
I could only run the Hello World with Karaf.

Using Karaf is quite interesting and was nice to learn it (inc. OSGi, Felix, etc). But I need to debug my application and I couldn't setup the Eclipse Pax Runner. I tried with Eclipse Neon 3 (4.6.3) but it doesn't work (the problem of Run Configuration). How should I proceed?

I'd like  your suggestion regarding the system I'm developing for real-time ECG monitoring. I'm using the Shimmer3 ECG device, which communicates with the Shimmer Capture Android app, which is implemented as a C# Xamarin project (.NET). I'd like to integrate this app with the uAAL context bus running in a server (in "the cloud"). What should I do? I thought in two solutions:
(a) If uAAL context bus provides a REST API, I can change the Shimmer Android app to submit data to this API (via comoom HTTP request). 
(b) If not, I wonder how to integrate the Shimmer Android app with uAAL Android app. I wouldn't like to have a creepy solution of saving the data in a shared folder... 

Thanks in advance for the support.

Joao

**Comment by Alfiva** [comment]
Hi Joao,
Regarding your last questions, you can do:

a) You can do this if you setup uAAL as a "server" and use the REST API manager: https://github.com/universAAL/remote/wiki/REST-API 

b) You can do this if you turn your app into an Android universAALized app, and you install the Android uAAL MW app as well: https://github.com/universAAL/nativeandroid/wiki/Adapting-or-developing-your-app-for-uAAL 

What to choose will depend on exactly what you want to do. In general, option b) is more complicated, but it is intended for having the phone behave like a regular uAAL node (seamless connection with other nodes whether in the same network or "outdoors"). If you are considering a more "simple" scenario of a phone connecting to a server occassionally, then option a) fits better and is as simple as using any other REST API.

**Comment by jonimoreira** [comment]
Thanks very much for this information, Alvaro! 
I'll try the REST API for the first POC. 
A quick question: I noticed that you're using JSON/XML for some data serialization (e.g. Space) and text/plain for the ontologies (RDF/Turtle). For this second, why not JSON-LD?

**Comment by Alfiva** [comment]
Yes, I have it on my radar/to-do list, but in this first iteration it was simpler to go with turtle, which I can feed directly into the universAAL parser. (With JSON-LD I would have to make an intermediate parsing, which I could do with rdf4j, I think, but I need the time to do it)

**Comment by amedranogil** [comment]
I think better than having intermediate parser, have universAAL core alternative parser for JSON-LD.
Added: https://github.com/universAAL/middleware/issues/487

**Comment by amedranogil** [comment]
@jonimoreira After your previous comment we have been improving the documentation.

Your new comment will definitelly help us improve more. Let me answer very quickly

> It took me some time to discover that "features:" is "feature:", "addurl" is "repo-add", "bundle:list" to see the ids, among other things.

The different commands come from the fact of using different versions of Karaf. e.g: karaf 2.x will accept "features" and "feature" indistinguishly, but karaf3.+ will not. Karaf3.+ shell had a refactoring to put order in the commands, thus some commands had changed. **we must update this information in the wiki**. for starters, I plan to create a wiki page exclusively on karaf commands, also so we can link to this page which explains commands from the other tutorials.

> In two Karaf instances I could run but not to set one as peer

It is not mandatory to have one as peer. 2, more, coordinators will interact fine (in most cases). This explanation might be old, **we need to synch explanations like this with middleware wiki**. Also addressing this issue, I am planning on creating a wiki page on all configuration propoerties, similar to commands page.

> But I need to debug my application and I couldn't setup the Eclipse Pax Runner

There is the possiblity to [debug your applciations running on karaf from eclipse.](https://github.com/universAAL/distro.karaf/wiki/Developing-in-Karaf-tips#how-to-debug-your-application-with-karaf). I have some doubts that the documentation is up to date, but the general gist is there. The latest versions of the distro are already configured for debugging by default, check the JMX port on the karaf script, and also ensure your eclipse run configuration has included all the source code it needs.

**Comment by jonimoreira** [comment]
@Alfiva I tried to follow the steps on https://github.com/universAAL/remote/wiki/REST-API and I got stuck on step 6 of the installation. 

> On step 4, I assumed that it is bundle:install , right? It installs the bundle but with state Installed¨

> On step 5 I reseted  Karaf with system:shutdown -r 
Is this the correct way?

> On Step 6 I tried feature:install uAAL-RI.RESTAPI and the following error happens:

Error executing command: Can't install feature uAAL-RI.RESTAPI/0.0.0: 	
Error resolving artifact org.universAAL.support:uAAL.utils:jar:3.4.1-SNAPSHOT: Could not transfer artifact org.universAAL.support:uAAL.utils:jar:3.4.1-SNAPSHOT from/to uAAL-snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/support/uAAL.utils/3.4.1-SNAPSHOT/uAAL.utils-3.4.1-SNAPSHOT.jar. Return code is: 503 , ReasonPhrase:Service Unavailable.

Obs.1: I can see uAAL-RI.RESTAPI in feature:list
Obs.2: feature:install uAAL-RI.RESTAPI/3.4.1-SNAPSHOT produces the same error

> I tried to follow the "manually" part: 

> feature:install http
It installs but does not add any bundles.

> bundle:install mvn:org.apache.derby/derby/10.10.1.1
Works well, I can see the bundle, but with state "Installed".

> bundle:install mvn:com.google.android.gcm/gcm-server/1.0.3
Bundle IDs: 
Error executing command: Error installing bundles:
	Unable to install bundle mvn:com.google.android.gcm/gcm-server/1.0.3

> bundle:install mvn:org.universAAL.remote/ri.rest.manager/3.4.1-SNAPSHOT
Bundle IDs: 
Error executing command: Error installing bundles:
	Unable to install bundle mvn:org.universAAL.remote/ri.rest.manager/3.4.1-SNAPSHOT


Can you give me some support to deploy this REST API, please? Thanks!

**Comment by Alfiva** [comment]
First of all, did you follow this?

> If you use [Karaf](https://github.com/universAAL/distro.karaf) you can just install the feature uAAL-RI.RESTAPI from the Remote Interoperability Karaf features, which includes everything.

That's before any "step" which are just there

> If you want to use Karaf 4.X or are having trouble with the feature, you can follow these steps

So if you have managed to run universAAL you just need to do feature:install uAAL-RI.RESTAPI.
If for whatever reason you must follow the "steps", notice the footnote in step 1 (which means I should probably put it in there, not in a footnote)

> You can use our 3.0.X distros from distro.karaf repo. But if you want to prepare one yourself, just download it from Apache Karaf and perform these changes:....

Without the steps in that footnote you will not be able to download anything from uAAL.
So please try first without any of those extra steps. If you have uAAL running somewhere, just try installing the feature.

**Comment by Alfiva** [comment]
About that "Return code is: 503 , ReasonPhrase:Service Unavailable."
I just realized our Maven repository is currently down. We will try to get it up soon. Sorry.

**Comment by amedranogil** [comment]
on the mean time you can install locally the missing components. Concetely in your case:

1. checkout https://github.com/universAAL/utilities
2. checkout the version you need (in your case git checkout 3.4.1-SNAPSHOT)
2. open commandline in utilities.pom/
3. mvn install

This should be enough to get the component in your local repo, so that your karaf can locate it.

**Comment by jonimoreira** [comment]
@amedranogil , I just did and it seems a similar issue regarding the Maven server (Service Unavailable). 

Is there another way to deploy the REST API? 

Error message:
```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not transfer artifact org.universAAL.middleware:mw.pom.core:pom:3.4.1-SNAPSHOT from/to uaal-snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/middleware/mw.pom.core/3.4.1-SNAPSHOT/mw.pom.core-3.4.1-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. @ line 30, column 19
[ERROR] Non-resolvable import POM: Could not transfer artifact org.universAAL.middleware:mw.pom.osgi:pom:3.4.1-SNAPSHOT from/to uaal-snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/middleware/mw.pom.osgi/3.4.1-SNAPSHOT/mw.pom.osgi-3.4.1-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. @ line 37, column 19
[ERROR] Non-resolvable import POM: Could not transfer artifact org.universAAL.ontology:ont.pom:pom:3.4.1-SNAPSHOT from/to uaal-snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/ontology/ont.pom/3.4.1-SNAPSHOT/ont.pom-3.4.1-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. @ line 44, column 19
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.universAAL.support:utilities.pom:3.4.1-SNAPSHOT (/home/joao/UniversAAL/Example03_RESTAPI_02/utilities-3.4.1-SNAPSHOT/utilities.pom/pom.xml) has 3 errors
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.universAAL.middleware:mw.pom.core:pom:3.4.1-SNAPSHOT from/to uaal-snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/middleware/mw.pom.core/3.4.1-SNAPSHOT/mw.pom.core-3.4.1-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. @ line 30, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.universAAL.middleware:mw.pom.osgi:pom:3.4.1-SNAPSHOT from/to uaal-snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/middleware/mw.pom.osgi/3.4.1-SNAPSHOT/mw.pom.osgi-3.4.1-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. @ line 37, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.universAAL.ontology:ont.pom:pom:3.4.1-SNAPSHOT from/to uaal-snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/ontology/ont.pom/3.4.1-SNAPSHOT/ont.pom-3.4.1-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. @ line 44, column 19 -> [Help 2]
```

**Comment by amedranogil** [comment]
Yep, sorry I missed the dependencies.
You can always build universAAL locally: https://github.com/universAAL/platform/wiki/Building-from-Source

**Comment by jonimoreira** [comment]
@amedranogil , having the same error in step 4 of "building from source" (Service Unavailable):
>> 4.go to uAAL.pom and install:

Any other option? 

Error message:
```
[ERROR] The build could not read 13 projects -> [Help 1]
[ERROR]   
[ERROR]   The project org.universAAL.support:maven.pom:3.4.2-SNAPSHOT (/home/joao/UniversAAL/Example04_BuildFromSource/platform/xtras/maven/maven.pom/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.universAAL.support:maven.pom:3.4.2-SNAPSHOT: Could not transfer artifact org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from/to uaal-snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/uAAL.pom/3.4.2-SNAPSHOT/uAAL.pom-3.4.2-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.universAAL.support:itests.pom:3.4.2-SNAPSHOT (/home/joao/UniversAAL/Example04_BuildFromSource/platform/xtras/itests/itests.pom/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.universAAL.support:itests.pom:3.4.2-SNAPSHOT: Failure to transfer org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from http://depot.universaal.org/maven-repo/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of uaal-snapshots has elapsed or updates are forced. Original error: Could not transfer artifact org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from/to uaal-snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/uAAL.pom/3.4.2-SNAPSHOT/uAAL.pom-3.4.2-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.universAAL.support:utilities.pom:3.4.2-SNAPSHOT (/home/joao/UniversAAL/Example04_BuildFromSource/platform/xtras/utilities/utilities.pom/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.universAAL.support:utilities.pom:3.4.2-SNAPSHOT: Failure to transfer org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from http://depot.universaal.org/maven-repo/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of uaal-snapshots has elapsed or updates are forced. Original error: Could not transfer artifact org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from/to uaal-snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/uAAL.pom/3.4.2-SNAPSHOT/uAAL.pom-3.4.2-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.universAAL.middleware:mw.pom:3.4.2-SNAPSHOT (/home/joao/UniversAAL/Example04_BuildFromSource/platform/middleware/pom/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.universAAL.middleware:mw.pom:3.4.2-SNAPSHOT: Could not transfer artifact org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from/to uaal_snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/uAAL.pom/3.4.2-SNAPSHOT/uAAL.pom-3.4.2-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.universAAL.ontology:ont.pom:3.4.2-SNAPSHOT (/home/joao/UniversAAL/Example04_BuildFromSource/platform/ontology/ont.pom/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.universAAL.ontology:ont.pom:3.4.2-SNAPSHOT: Failure to transfer org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from http://depot.universaal.org/maven-repo/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of uaal-snapshots has elapsed or updates are forced. Original error: Could not transfer artifact org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from/to uaal_snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/uAAL.pom/3.4.2-SNAPSHOT/uAAL.pom-3.4.2-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.universAAL.context:ctxt.pom:3.4.2-SNAPSHOT (/home/joao/UniversAAL/Example04_BuildFromSource/platform/context/ctxt.pom/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.universAAL.context:ctxt.pom:3.4.2-SNAPSHOT: Failure to transfer org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from http://depot.universaal.org/maven-repo/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of uaal-snapshots has elapsed or updates are forced. Original error: Could not transfer artifact org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from/to uaal_snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/uAAL.pom/3.4.2-SNAPSHOT/uAAL.pom-3.4.2-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.universAAL.lddi:lddi.pom:3.4.2-SNAPSHOT (/home/joao/UniversAAL/Example04_BuildFromSource/platform/lddi/lddi.pom/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.universAAL.lddi:lddi.pom:3.4.2-SNAPSHOT: Failure to transfer org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from http://depot.universaal.org/maven-repo/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of uaal_snapshots has elapsed or updates are forced. Original error: Could not transfer artifact org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from/to uaal_snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/uAAL.pom/3.4.2-SNAPSHOT/uAAL.pom-3.4.2-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.universAAL.security:security.pom:3.4.2-SNAPSHOT (/home/joao/UniversAAL/Example04_BuildFromSource/platform/security/security.pom/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.universAAL.security:security.pom:3.4.2-SNAPSHOT: Failure to transfer org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from http://depot.universaal.org/maven-repo/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of uaal-snapshots has elapsed or updates are forced. Original error: Could not transfer artifact org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from/to uaal_snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/uAAL.pom/3.4.2-SNAPSHOT/uAAL.pom-3.4.2-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.universAAL.remote:ri.pom:3.4.2-SNAPSHOT (/home/joao/UniversAAL/Example04_BuildFromSource/platform/remote/ri.pom/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.universAAL.remote:ri.pom:3.4.2-SNAPSHOT: Failure to transfer org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from http://depot.universaal.org/maven-repo/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of uaal-snapshots has elapsed or updates are forced. Original error: Could not transfer artifact org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from/to uaal_snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/uAAL.pom/3.4.2-SNAPSHOT/uAAL.pom-3.4.2-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.universAAL.service:srvc.pom:3.4.2-SNAPSHOT (/home/joao/UniversAAL/Example04_BuildFromSource/platform/service/srvc.pom/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.universAAL.service:srvc.pom:3.4.2-SNAPSHOT: Failure to transfer org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from http://depot.universaal.org/maven-repo/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of uaal-snapshots has elapsed or updates are forced. Original error: Could not transfer artifact org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from/to uaal_snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/uAAL.pom/3.4.2-SNAPSHOT/uAAL.pom-3.4.2-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.universAAL.ui:ui.pom:3.4.2-SNAPSHOT (/home/joao/UniversAAL/Example04_BuildFromSource/platform/ui/ui.pom/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.universAAL.ui:ui.pom:3.4.2-SNAPSHOT: Could not transfer artifact org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from/to snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/uAAL.pom/3.4.2-SNAPSHOT/uAAL.pom-3.4.2-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.universAAL.support.samples:samples.pom:3.4.2-SNAPSHOT (/home/joao/UniversAAL/Example04_BuildFromSource/platform/xtras/samples/samples.pom/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.universAAL.support.samples:samples.pom:3.4.2-SNAPSHOT: Failure to transfer org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from http://depot.universaal.org/maven-repo/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of uaal-snapshots has elapsed or updates are forced. Original error: Could not transfer artifact org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from/to snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/uAAL.pom/3.4.2-SNAPSHOT/uAAL.pom-3.4.2-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.universAAL.tools:tools.pom:3.4.2-SNAPSHOT (/home/joao/UniversAAL/Example04_BuildFromSource/platform/xtras/tools.runtime/tools.pom/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.universAAL.tools:tools.pom:3.4.2-SNAPSHOT: Failure to transfer org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from http://depot.universaal.org/maven-repo/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of uaal-snapshots has elapsed or updates are forced. Original error: Could not transfer artifact org.universAAL:uAAL.pom:pom:3.4.2-SNAPSHOT from/to snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/universAAL/uAAL.pom/3.4.2-SNAPSHOT/uAAL.pom-3.4.2-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR] 
```

**Comment by amedranogil** [comment]
> Any other option?

yes continue reading :stuck_out_tongue: :

 `if working offline (or if the previous command reports some artefact is missing)` 

we are all effectively working off line until nexus server is restarted. All your errors are "missing Artifacts", which are needed before compiling, fortunatelly they are not many. 
```
cd xtras/maven/plugins
mvn install
cd ../../../uAAL.pom
mvn install -N
mvn install
```

BTW, notice you are building 3.4.2-SNAPSHOT instead of 3.4.1-SNAPSHOT (from your previous comments) please also read [about how to check out other versions](https://github.com/universAAL/platform/wiki/Building-from-Source#tips) (if you already have performed step 3, you may repeat it)

**Comment by jonimoreira** [comment]
These built successfully:
>> xtras/maven/plugins 
>> mvn install -N

But the last mvn install failed, the same error. 
Is it possible if someone experienced with uAAL deploys the REST API in a clean environment (VM) and provide the detailed instructions and/or share the VM, please? 

Error message:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:09 min
[INFO] Finished at: 2018-03-16T12:03:12+01:00
[INFO] Final Memory: 143M/342M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project itests: Could not resolve dependencies for project org.universAAL.support:itests:bundle:3.4.1-SNAPSHOT: Failed to collect dependencies at org.springframework.osgi:log4j.osgi:jar:1.2.15-SNAPSHOT: Failed to read artifact descriptor for org.springframework.osgi:log4j.osgi:jar:1.2.15-SNAPSHOT: Could not transfer artifact org.springframework.osgi:log4j.osgi:pom:1.2.15-SNAPSHOT from/to uaal-snapshots (http://depot.universaal.org/maven-repo/snapshots/): Failed to transfer file: http://depot.universaal.org/maven-repo/snapshots/org/springframework/osgi/log4j.osgi/1.2.15-SNAPSHOT/log4j.osgi-1.2.15-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. -> [Help 1]
```

**Comment by amedranogil** [comment]
Unfortunately the component you are missing is in the same nexus server.
you could try either 

- compile 3.4.0 version (that may not be dependant on a snapshot version), if you have code for 3.4.1-SNAPSHOT, it should run on 3.4.0
- download [3.4.0 karaf release](https://github.com/universAAL/distro.karaf/files/1815142/distro.karaf-3.4.0.zip).

Apologies for all the inconvenience we are currently trying to fix the nexus server, which would have avoided all this trouble. 

on our side:

- We are working on a docker image also, but unfortunatly this is not available now.
- We could look for the configuration for your maven to locate alternative nexus repositories (which are working) (and probably add a wiki for these cases)
- We could look into the dependency and remove it from 3.4.1-SNAPSHOT so a clean build works. Unfortunately I remember having no success with this long time ago.

I will let you know.

Added issue: https://github.com/universAAL/itests/issues/4

**Comment by amedranogil** [comment]
Try adding this to your ~/.m2/settings.xml
```
	<mirrors>
		<mirror>
			<id>uAAL-release-mirror1</id>
			<url>http://nexus.lst.tfo.upm.es/content/groups/public/</url>
			<mirrorOf>uaal,uaal-thirdparty</mirrorOf>
		</mirror>
		<mirror>
			<id>uAAL-snapshot-mirror1</id>
			<url>http://nexus.lst.tfo.upm.es/content/groups/public/</url>
			<mirrorOf>uaal-snapshots,uaal_snapshots,uaal-thirdparty-snapshots</mirrorOf>
		</mirror>
	</mirrors>
```
It is commented in the example [settings.xml](https://github.com/universAAL/maven/blob/master/maven-repo-settings/settings.xml).
This add one of our mirrors of the nexus repository, helps getting all the missing artifacts (everyting above should be solved with this).

**Comment by amedranogil** [comment]
@jonimoreira  Servers are back online, and you should now be able to simply follow the instructions to get universAAL running with the REST-API. 
If you are still experiencing problems don't hesitate to ask.

**Comment by jonimoreira** [comment]
Hi @amedranogil, 

Now I can install and run the REST API but I still have some issues/questions: 
1) I'm doing: 
```
feature:install uAAL-RI.RESTAPI
bundle:list
start <id of REST-API Manager> 
```

When requesting the REST through the browser (Firefox) to list the spaces ( http://localhost:9000/uaal/spaces ), the return is an empty list:
`<spaces><link href="/uaal/spaces" rel="self"/></spaces>`

I thought it could be something related with authentication, then I run:
`curl -u joao:<mypassword> localhost:9000/uaal/spaces/`

And the output is the same (empty list of spaces):
`{"spaces":{"link":{"@href":"/uaal/spaces","@rel":"self"}}}`

In Karaf I can list the default space through: 
`universAAL:spaces`

 Found: 1 AAL Spaces
 ----------------------------------------
 * myHome3 - Super Domestic Home - 8888 - 6735d916-357b-4a79-adfc-3d2039b23c60 - mw.modules.aalspace.osgi - http://aaloa.isti.cnr.it/udp.xml 

Am I'm missing something? After installing the REST-API I can see these new bundles:
138 | Active |  59 | 3.0.2                 | Apache CXF Runtime HTTP Jetty Transport                     
139 | Active |  60 | 0                     | wrap_mvn_org.universAAL.support_uAAL.utils_3.4.1-SNAPSHOT   
140 | Active |  60 | 10.10.1000001.1458268 | Apache Derby 10.10                                          
141 | Active |  60 | 0                     | wrap_mvn_com.googlecode.json-simple_json-simple_1.1         
142 | Active |  60 | 0                     | wrap_mvn_com.google.android.gcm_gcm-server_1.0.2            
143 | Active |  70 | 3.4.1.SNAPSHOT        | universAAL Remote Interoperability REST-API Manager

I tried starting one by one, but didn't work. Also, I tried adding the configuration properties of the REST API wiki, no success.

What I'd like to do now is a simple "Hello World":
- run the REST API
- test the GET methods
- test a publisher submitting data (using any ontology, preferably health domain), can be via command line
- test a subscriber receiving the data published, can be via command line


2) When I list the features, I see 3 remote APIs:
uAAL-RI.RAPI                                    | 3.4.1-SNAPSHOT   |           | universAAL-RemoteInteroperability | Remote API.                                       
uAAL-RI.RESTAPI                                 | 3.4.1-SNAPSHOT   |           | universAAL-RemoteInteroperability | Remote API.                                       
uAAL-RI.RAPI.MySQL                              | 3.4.1-SNAPSHOT   |           | universAAL-RemoteInteroperability | Remote API MySQL.

Should I install the other 2 ones? (RAPI and RAPI.MySQL)


3) I understood that the internal DB of uAAL is an Apache Derby instance, right? And in this DB all "entities" are stored, like spaces, ontologies, as well as publishers and subscribers. Is this correct? If so, how can I access directly the DB to check the tables and run some SQL queries there? I imagine that the distro.karaf does the job of installing the DB, right? 


4) I see some similarities between the concepts of publisher and caller, and between subscriber and "callee", what are the differences? 
The table describing the REST API methods (https://github.com/universAAL/remote/wiki/REST-API) lacks on a description for each method, this would be helpful to understand such difference. For example, the POST method of /callers/{mycer} submits data as TTL, is this how the device publishes a measurement? Or this is done through the POST method of /publishers/{mypub}? 


5) I see some similarities of the context event patterns with complex event processing (CEP) rules. What are the differences? Does uAAL use an existing CEP engine? 


6) In my project I'd like to:
- Integrate Shimmer3 ECG mobile app (acting as a publisher) with uAAL (acting as a context broker), which will be linked with the INTER-IoT middleware through the bridges under development by the project. My emergency system will subscribe to INTER-IoT to receive the data. If you want more information I have a recent paper in I-ESA 2018 about it. 

- Use my own ontology for ECG data, which is an extension of SAREF based on HL7 FHIR. I read the current guidelines for this (in https://github.com/universAAL/ontology/wiki/Guidelines) and I wonder whether this is up-to-date, I noticed that the last update was in 2015... Moreover, I noticed that, although OWL is mentioned, the ontology structure is implemented as Java classes. Is there a way to generate these Java classes from my OWL (or TTL) file? What would be the best approach? Implementing each class and object/data property? One detail from my ontology is that it reuses a number of existing predicates of other ontologies through "owl imports" (e.g. SAREF, SAREF4envi, W3C QU, M3, etc), I wonder if this can be an issue with uAAL?

- The Shimmer3 ECG mobile app (C#) is already changed to submit data according to my ontology, right now it works well publishing the data (as JSON-LD) to a Mosquitto broker. The idea is to change from Mosquitto to uAAL (via REST too), changing to uAAL serialization (as I understood TTL with text/plain). 

- Once these tasks are done, just profit: receive the data through the application layer of INTER-IoT framework. 

Thanks in advance for the support!

PS: Let me know if here is not the appropriate channel for these Q&A, if you prefer we can discuss via e-mail or even a telco.

**Comment by amedranogil** [comment]
For all Rest API questions the best one to answer is @Alfiva .
Maybe it would be nice to "move" the last post to remote interoperability issue, or to a new issue in the general platform space; to be found easier by people experiencing your same problems.

**Comment by Alfiva** [comment]
Hi @jonimoreira , sorry for the delay, I was on vacation. I agree this issue has grown outside its original opic so it could be moved to https://github.com/universAAL/remote or if we can keep discussing via email, since you have different inquiries that are project-specific. Regardless, I will try to answer some of those questions here:

1-When accessing the REST API /spaces URL from a browser (or any other tool) first, it should ask you for credentials (by default REST API is configured to accept any and store them in its DB). Once you get there, yes, there is at first an empty list of spaces. This is because in the REST API "spaces" = "tenants" (learn more in https://github.com/universAAL/remote/wiki/uSpace-Gateway). So you do have a default uAAL space in the Karaf instance, but in REST API you will only see the spaces (tenants) you create through the REST API. You will need to create at least one to actually do something of course. By default all tenants (spaces) communicate with all others but you can restrict that (https://github.com/universAAL/remote/wiki/uSpace-Gateway#Tenantaware_applications)

2- RAPI is a non-REST, POST-based remote API that in practice is superseded by REST API, so please just ignore it.

3- The DB is located, by default, in {karaf}\data\ri.rest.manager\RESTPersistence. You can use any Apache Derby to access the content there, but I recommend actually using the REST API to read its contents (the only thing you can't brose is credentials).

4- I recommend you familiraize with the core concepts of universAAL of Context and Service before using the API. Refer to https://github.com/universAAL/platform/wiki and read the theory (non-Hello World) links, starting wtih https://github.com/universAAL/platform/wiki/Understanding-universAAL. I assume for what you want to do you will have enough with Context bus.

5- Context Event Patterns are like "filters" for events. In that regard, they are like the "trigger/input" part of Complex Event Processing. In uAAL the Situation Reasoner(https://github.com/universAAL/context/wiki/Situation-Reasoner) and the ASOR(https://github.com/universAAL/service/wiki/Service-Orchestration) can play that role.

6- Once you go through all the above I think you will have a clearer idea of how it can be implemented. We can keep discussing via email.

**Comment by cstockloew** [comment]
This thread is getting a bit too long and many things have been resolved already; I think it's better to stop at this point. If another issue occurs, please open a new issue in the appropriate repo.

One last remark:
I just uploaded a new version of the tools, please
Install Eclipse Modelling Tools version 4.6 (Neon)
Install Eclipse Plugins from http://depot.universaal.org/eclipse-update/4.6/ 
This should fix (some of) the remaining issues.
